frc-862/thunder

- auto/AutonomousCommandFactory.java
fixed the makeTrajectory method to be more abstract and not require a drivetrain now, but uses constructor to set all the necessary methods and parameters to make pathplanner trajectories.
> 10 fix auton command factory

- auto/AutonomousCommandFactory.java
added manual trajectoy generation
> [#12] added method to generate a two or more point path on the fly

- LightningRobot.java
- auto/AutonomousCommandFactory.java
Connected the robot to the Path Planner Server
> [#9] Added connection to Path Planner Server

- config/NeoConfig.java
> 17 neo config

- tuning/StaticFFTuner.java
added mutli motor function to static ff tuner
> [#21] added multi motor static ff tuning

- swervelib/SteerController.java
- swervelib/SwerveModule.java
- swervelib/SwerveModuleFactory.java
- swervelib/ctre/Falcon500SteerControllerFactoryBuilder.java
- swervelib/rev/NeoSteerControllerFactoryBuilder.java
Added some logging and a method to resync the module encoders so that we dont have the weired module offset issue. Im implementing this now so that we can move on to some more important issues, but this might have to be readdressed later. Closes #23
> 23 module angle bug

- shuffleboard/LightningShuffleboard.java
checks if shuffleboard component  exists, and if not, creates it. if it does exist, simply update it/retrieve value from it using networktables. has setter/getter functions for doubles, booleans, and strings. should be easy enough to implement widgets as well, if necessary
closes [#30]
> [#30] working shuffleboard creator

- config/SparkMaxPIDGains.java
- swervelib/DriveController.java
- swervelib/Mk3SwerveModuleHelper.java
- swervelib/Mk4ModuleConfiguration.java
- swervelib/Mk4SwerveModuleHelper.java
- swervelib/Mk4iSwerveModuleHelper.java
- swervelib/SwerveModule.java
- swervelib/SwerveModuleFactory.java
- swervelib/ctre/Falcon500DriveControllerFactoryBuilder.java
- swervelib/ctre/Falcon500SteerConfiguration.java
- swervelib/ctre/Falcon500SteerControllerFactoryBuilder.java
- swervelib/rev/NeoDriveControllerFactoryBuilder.java
somewhat fixed drive issue with pid stuff Closes #36
> 36 fix drive issue

- limelightlib/LimelightHelpers.java
fixed it *ahem* chris *ahem*
closes #41
> [#41] added correct package

- config/NeoConfig.java
- config/SparkMaxPIDGains.java
- swervelib/Mk4iSwerveModuleHelper.java
- swervelib/rev/NeoDriveControllerFactoryBuilder.java
added code to use spark max pid gains class instead of raw PID values. Closes #38
> [#38] made changes to have neoconfig use sparkmaxpidgains

- config/NeoConfig.java
> 45 set pid controller feedback device

- auto/AutonomousCommandFactory.java
added method to create path points easier, also added javadocs. Closes #49
> [#49] added method to create path points easier, also added javadocs

- tuning/PIDDashboardTuner.java
fixed issue with spark max pid controller tuner, and added check to fix loop over run hopefully Closes #59
> [#59] fixed tuner issue

- shuffleboard/LightningShuffleboard.java
uses arrays. you still have to set the array entry as a graph in shuffleboard
closes #63
> [#63] made creategraph function

- hardware/PicoColorSensor.java
uses https://github.com/ThadHouse/picocolorsensor
closes #61
> [#61] implemented color sensor for use from a raspi pico

- shuffleboard/LightningShuffleboard.java
> [#43] added support for suppliers and arrays

- pathplanner/com/pathplanner/lib/commands/PPSwerveControllerCommand.java
added logging for targets in our paths. Closes #66
> [#66] added logging for targets for our paths

- LightningRobot.java
To find the logs, open "Data Log Tool" on your driverstation (downloaded with other wpilib applications such as smartdashboard). Go to download tab in the bottom left and set team number/address to 10.8.62.2 (address of RIO), set username to lvuser, and keep password blank. If the connection is made after logs are created you can just hit the download button and select a file path. Load the file onto AdvantageScope and just select which graphs you want to view. not tested on an actual robot yet but have used a spare roborio and it worked (gave the file) although it gave no values.
> Starts WPILIB Data Logging (finished)

- limelightlib/Pipelines/Retro_2.vpr
- limelightlib/Pipelines/Retro_3.vpr
Updated the retroreflective pipelines to use single targeting instead of smart targeting.
> [#73] Updated the retroreflective pipelines

- LightningRobot.java
- shuffleboard/LightningShuffleboard.java
Stats the wpilib logger with driverstation logging Closes #25
> [#25] add wpilib data logging and added driverstation logging aswell

- shuffleboard/LightningShuffleboardPeriodic.java
if you've got questions just ask me
have fun reviewing :)
(closes #77)
> 77 periodic shuffleboard

- auto/AutonomousCommandFactory.java
- pathplanner/com/pathplanner/lib/PathPlanner.java
- pathplanner/com/pathplanner/lib/PathPlannerTrajectory.java
- pathplanner/com/pathplanner/lib/PathPoint.java
- pathplanner/com/pathplanner/lib/auto/SwerveAutoBuilder.java
- pathplanner/com/pathplanner/lib/commands/FollowPathWithEvents.java
- pathplanner/com/pathplanner/lib/commands/PPSwerveControllerCommand.java
added changes to help with manual trajectories
> 86 manual trajectory

- LightningRobot.java
- limelightlib/LimelightHelpers.java
- vision/LimelightBase.java
> 89 parse json

- util/Pose4d.java
- util/PoseConverter.java
- vision/Limelight.java
> 102 lag police

- vision/Limelight.java
- vision/targeting/FiducialResult.java
- vision/targeting/NeuralClassifierResult.java
- vision/targeting/NeuralDetectorResult.java
- vision/targeting/RetroreflectiveResult.java
- vision/targeting/TargetingResult.java
PLEASE this should've been merged like a month ago 😭
> Json dumps

- math/LightningMath.java
Added an old math function for void
> Added constrain

- filter/XboxControllerFilter.java
> 83 xboxcontroller filter

- config/FalconConfig.java
> 112 add ks and kv to falcon config

- vision/Limelight.java
switched vision and field limit
closes #117
> [117] fix limelight filtering

- vision/Limelight.java
> added limelight.getName()

- LightningContainer.java
> [#125] Added function to create named commands

- math/OTFShootingMath.java
meant to merge this a while ago but here it is :)
closes #122
> 122 otf shooting math

- config/FalconConfig.java
- hardware/ThunderBird.java
- hardware/ThunderTalonFX.java
> 136 falconconfig restructure

- LightningRobot.java
Change CPU clock speed on roborio from 20ms to 10ms
> Speed it up

- testing/SystemTest.java
- testing/SystemTestCommand.java
- testing/SystemTestCommandGroup.java
> [#134] add cancel behavior

- hardware/ThunderBird.java
- tuning/FalconTuner.java
- tuning/SlotConfiguration.java
> 128 added falcon dashboard tuner

- filter/XboxControllerFilter.java
Can now use filtered controller as full controller
Closes #141
> [#141] Extends controller

- tuning/FalconTuner.java
> [#143] - added motion magic tuning to FalconTuner

- tuning/FalconTuner.java
actually closes #143 
java didnt wanna work and i thought my code was correct lol
> [#143] - fixed errors

- filter/XboxControllerFilter.java
> [#146] Fixed Filters

- hardware/ThunderBird.java
> [#150] Added Check for proper config

- filter/XboxControllerFilter.java
- math/LightningMath.java
- vision/Limelight.java
> [#148] fixed controller filter

- hardware/ThunderBird.java
> [#152] all caps warning and see also in docs for thunderbird

- filter/XboxControllerFilter.java
> [#141] update controller filter

- hardware/ThunderBird.java
> [#155] added ramprate to motors

- vision/Limelight.java
> [#164] - added new limelight changes

- hardware/ThunderBird.java
- util/Pose4d.java
meow
the only thing here is to fix all syntax things so it will build with 2025 code
> 2025 Changes

- shuffleboard/LightningShuffleboard.java
> [#177] i completely rewwrote it and it works in sim. yippee?

- hardware/Thunderbolt.java
> [#182] sorrryyyyyyy

- leds/LightningColors.java
- leds/LightningLEDs.java
- leds/ThunderStrip.java
- leds/Thunderbolt.java
> [#187] renamed for clarity and added enablestatefor

- util/FieldParse.java
> [#188] - added function for parsing wpical output
